### ISSUE TITLE
Active first tab ::after overlaps tab left border and shadow

### ISSUE THREAD

**Issue by ghost** [insanityfarm/hyperterm-mactabs#3]
First tab is active:

<img width="240" alt="screen shot 2017-03-16 at 16 17 52" src="https://cloud.githubusercontent.com/assets/8956796/23997861/2a853e4c-0a64-11e7-98f6-80a5dd979f79.png">

Next tab is active:

<img width="265" alt="screen shot 2017-03-16 at 16 17 43" src="https://cloud.githubusercontent.com/assets/8956796/23997889/3dc9f7c2-0a64-11e7-9468-b572fa9a0185.png">

**Comment by insanityfarm** [comment]
Thanks for reporting it! I must've missed the notification when you posted this, sorry I didn't see it until now. I've fixed this issue in v1.0.7.
